Mvc_Repository/Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using Mvc_Repository.Models;
using Mvc_Repository.Models.ViewModel;

namespace Mvc_Repository.Controllers
{
    public class UploadFileController : MemberController
    {
        TestEntities db = new TestEntities();
        public ActionResult Index()
        {
            return View();
        }
        // GET: UploadFile
        public ActionResult Upload_Multiple()
        {
            return View();
        }
        public ActionResult Uploaded(HttpPostedFileBase[] files)
        {
            if (files.Count() > 0)
            {
                foreach (var uploadFile in files)
                {
                    if (uploadFile.ContentLength > 0)
                    {
                        string savePath = Server.MapPath("~/Files/");
                        uploadFile.SaveAs(savePath + uploadFile.FileName);
                    }
                }
            }

            return RedirectToAction("Upload_Multiple");
        }
        public ActionResult GetJSON()
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<CateResult> result = db.Categories.Select(x => new CateResult()
            {
                CategoryID = x.CategoryID,
                CategoryName = x.CategoryName,
                Description = x.Description
            }).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult postedJson(ArgObject arg)
        {
            JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            return new JsonResult()
            {
                Data = arg
            };
        }
        public ActionResult TestScript()
        {
            string[] abc = { "a", "b", "c", "d", "e", "f" };
            string kkdd = "'" + string.Join("','", abc) + "'";
            return View("/Views/UploadFile/TestScript.cshtml", null, kkdd);
        }
        public ActionResult TestScript2()
        {
           
            return View();
        }
        public ActionResult TestScript3()
        {
            return View();
        }
        public ActionResult TestOpen()
        {
            return View();
        }
        public ActionResult TestOpen2()
        {
            return View();
        }
        public ActionResult W3CScript()
        {
            return View();
        }
        public ActionResult W3CScript2()
        {
            return View();
        }
        public ActionResult GetPart()
        {
            return PartialView("TestPartialView");
        }
        public ActionResult GetSession()
        {
            Session["member"] = new MemberViewModel()
            {
                MemberID = 1,
                MemberName = "Peter",
                MemberSex = "M"
            };
            return RedirectToAction("Index");
        }
        public ActionResult LoadSession()
        {
            ViewData["MemberID"] = CurrentMember.MemberID;
            ViewData["MemberName"] = CurrentMember.MemberName;
            ViewData["MemberSex"] = CurrentMember.MemberSex;
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
        }
        public class CateResult
        {
            public int CategoryID { get; set; }
            public string CategoryName { get; set; }
            public string Description { get; set; }
        }
        public class ArgObject
        {
            public string Name { get; set; }
            public SubArgObject SubArg { get; set; }
        }



        public class SubArgObject
        {
            public string PropA { get; set; }
            [JsonProperty("PropX")]
            public string PropB { get; set; }
            [ScriptIgnore]
            public string PropC { get; set; }
        }


    }
}

Mvc_Repository/Views/UploadFile/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section scripts{
    <script>
            var app = angular.module('myApp', []);
            app.service('WorldService', function () {
                this.name = "World";
            })
            app.service('JackService', function () {
                this.name = "Jack";
            })
            app.controller('MainController', ['JackService', function (NameService) {
                console.log(NameService.name);
            }])

        

    </script>
}
<div ng-controller="MainController"></div>

Mvc_Repository/Views/UploadFile/LoadSession.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LoadSession</title>
</head>
<body>
    <div> 
        @ViewData["MemberID"]
        <br />
        @ViewData["MemberName"]
        <br />
        @ViewData["MemberSex"]
    </div>
</body>
</html>

Mvc_Repository/Views/UploadFile/TestOpen.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TestOpen</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
    var Cwindow;
    $(function () {
        var f = document.forms[0];
        f.method = "GET";
        f.action = '@Url.Action("TestOpen2")';
        document.querySelector("#btn").onclick = function () {
            alert($('<div>').append($('#outer').clone()).html());
            return false;
        }
        $("#newWindow").click(function () {
            Cwindow = open('@Url.Action("TestOpen2")', "新視窗",
                "width=400,height=350,scrollbars=no,resizable=no");


            
        })
    })



    </script>
</head>
<body>
    <div> 
        <form>
            <input name="GetInput" value="lllo" type="text" id="sendInput" />
            <button id="newWindow">開啟新視窗</button>
            <label id="WindowReturn"></label>
            <a href="#" id="btn">按我</a>
            <input type="submit" value="送出" />
            <div id="outer"><span>這是測試</span></div>
        </form>
        
    </div>
    <script>
        
    </script>
</body>
</html>

Mvc_Repository/Views/UploadFile/TestOpen2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TestOpen2</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(function () {
            
            $("#GetValue").text($('#sendInput', opener.document).val());
            $("#CloseBtn").click(function () {
                
                $('#WindowReturn', opener.document).text($("#returnVal").val());
                window.close();
            })
        })
    </script>
</head>
<body>
    <div>
        <label id="GetValue"></label>
        <input name="GetReturnVal" type="text" id="returnVal" />
        <button id="CloseBtn">傳回母視窗並關閉</button>
    </div>
</body>
</html>

Mvc_Repository/Views/UploadFile/TestScript.cshtml
@model string
@{
    Layout = null;
    string abc = "123";
    int i;
    
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/testScript.js"></script>
<script>
    
    //亂數
    function fnRandom(iModifier) {
        return parseInt(Math.random() * iModifier);
    }
    //設定打開視窗的參數
    function fnSetValues() {
        var iHeight = oForm.oHeight.options[
            oForm.oHeight.selectedIndex].text;
        if (iHeight.indexOf("Random") > -1) {
            iHeight = fnRandom(document.body.clientHeight);
        }
        var sFeatures = "dialogHeight: " + iHeight + ";";
        return sFeatures;
    }
    function fnOpen() {
        //呼叫設定參數涵式
        var sFeatures = fnSetValues();

        //傳遞參數
        var sDialogArguments = document.getElementById("txtParent").value;
        //打開視窗

        var retValue = window.showModalDialog('@Url.Action("TestScript3")', sDialogArguments,
            sFeatures);
        //顯示返回值
        //alert(retValue);
        var divElement = document.getElementById("divChild");
        divElement.innerHTML = retValue;
    }
    function formSubmit() {
        document.getElementById("myForm").onsubmit = function () { }
        //document.forms.myForm.submit();
    }
    $(function () {
        $("#selitem").change(function () {
            $("#selitem option:selected").each(function () {
                var $this = $(this);
                if ($this.length) {
                    var selText = $this.text();
                    alert(selText);
                }
            })
            
          //alert(item);
        })
        $("#selection").click(function () {
            alert(window.getSelection().toString());
            return false;
        })
        $("#txtParent").on('input', function () {
            alert("input事件");
        });
        $("#inputtxt").click(function () {
            $("#txtParent").val("我得到了Text");
           
        })
        $(window).on('beforeunload', function () {
            return "真的要離開本頁?";
        });
        var editor = document.getElementById("editor");
        editor.contentDocument.designMode = "on";
        document.getElementById("main").style.color = "red";
        var elt = document.getElementById("shipping_address");
        $("body").append("<p id='hj'></p>");
        $("#hj").append("123");
    })
    
    
</script>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TestScript</title>
</head>
<body>
    <form id="myForm" onsubmit="alert('資料已送出')" onreset="alert('重置資料!')" method="get">
        <select style="width:100px" id="selitem">
            <option value="1">第一</option>
            <option value="2">第二</option>
            <option value="3">第三</option>
            <option value="4">第四</option>
            <option value="5">第五</option>
            <option value="6">第六</option>
            <option value="7">第七</option>
            <option value="8">第八</option>
        </select>

       <label><input type="checkbox" name="test" value="1" />1</label> 
       <label><input type="checkbox" name="test" value="2" />2</label> 
       <label><input type="checkbox" name="test" value="3" />3</label> 
       <input type="submit"  value="送出"/>
        <input type="reset" value="重置" />
    </form>
    <form name="oForm">
        Dialog Height
        <select name="oHeight">
            <option>-- Random --</option>
            <option>150</option>
            <option>200</option>
            <option>250</option>
            <option>300</option>
        </select>
        Create Modal Dialog Box

        本視窗(父):<input id="txtParent" type="text" />
        <input type="button" value="打開視窗" onclick="fnOpen()">
        <button id="inputtxt">輸入</button>
        來自子視窗:<div id="divChild"> 1</div>
        <script>
            document.write("<p>Title:" + document.title);
            document.write("<br>URL:" + document.URL);
            document.write("<br>Referred by " + document.referrer);
            document.write("<br>Modified on " + document.lastModified);
            document.write("<br>Accessed on " + new Date() + "</p>");
        </script>
       <iframe id="editor" src="about:blank"></iframe>
        <script>

        </script>
    </form>
    <button id="selection">你所選擇的文字</button>
    <p id="main">
        顯示CSS
    </p>
    <a href="http://tw.yahoo.com/">離開本頁</a>
</body>
</html>

Mvc_Repository/Views/UploadFile/TestScript2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script>
        // <!--[if IE 6]><![endif]-->

        $(function () {
            console.log($(document).height());
            $(window).scroll(function () {
                var scrollVal = $(this).scrollTop() + $(window).height();
                if (scrollVal == $(document).height())
                {
                    alert("已經在最底端");
                }
                $("span.qScrollTop").text(scrollVal);
            });
            function invoke(f, start, interval, end) {
                if (!start) start = 0;
                if (arguments.length <= 2)
                    setTimeout(f, start);
                else {
                    setTimeout(repeat, start);
                    function repeat() {
                        var h = setInterval(f, interval);
                        if (end) setTimeout(function () { clearInterval(h); }, end);
                    }
                }
            }

        });
    </script>
    <style>
        
    </style>


    <meta name="viewport" content="width=device-width" />
    <title>TestScript2</title>
</head>
<body>
    <div>
        <form method="post">
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <span style="color:red" class="qScrollTop"></span>
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <div id="terms">
                <h2>同意書</h2>
                <p>目前工作是網頁開發為主，因此針對了 HTML, JavaScript, CSS 等知識特別深入研究。若有任何問題，歡迎直接留言或是透過 Mail 討論。</p>

                <p>fontAvailable 是一個很有趣的外掛，它利用字型間的寬度差異性來判斷該字型是否有安裝。既然可以判斷是否有安裝就能針對沒安裝字型的來做設計囉。</p>
                <p>網頁設計人員都知道 HTML + CSS 是設計時不可或缺。但單純的靜態畫面不太能吸引瀏覽者的注意，所以得在搭配 JavaScript 來讓效果動起來。此次就用簡單的 jQuery 語法來讓原本單調的設計有不同的效果。</p>

                <p>如果你是看到預覽圖(感謝梅干熱情提供)而覺得裡面會有好康的話，建議可以按下 Alt + ← 來回到上一頁：如果你現在因為標題看不懂而感到莫名其妙的話，請不要覺得是自己的問題，因為筆者已經想不出範例名稱了XD！所以請忽略標題直接看下去。</p>

                <p>Img2DataURI 除了可以把圖片編碼成 DataURI 格式之外，也可以把編碼後的資料再轉回成圖片。如此一來就能偷偷的把別人的圖片還原囉(這不是這程式的主功能XD)！</p>

                <p class="red">當你按下送出申請鈕時，表示你看過且同意以上的內容！</p>
            </div>
            <input type="submit" name="submit" id="submit" value="送出申請" />
        </form>
    </div>
    
</body>
</html>

Mvc_Repository/Views/UploadFile/TestScript3.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript">
        //接收父視窗傳值
        function setValue() {
            document.getElementById("divFromParent").innerHTML = window.dialogArguments;

        }
        //返回父視窗，並回傳值
        function retParantWin() {
            //alert(document.getElementById("txtChild").value);
            window.returnValue = document.getElementById("txtChild").value;
            window.close();
        }
    </script>
    <title></title>
</head>
<body onload="setValue()">
    <form>
        Child

        父視窗傳值:<div id="divFromParent"> 1</div>
        本視窗(子)輸入:<input id="txtChild" type="text" />
        <input id="Button1" type="button" value="返回父視窗" onclick="retParantWin();" />
    </form>
</body>
</html>

Mvc_Repository/Views/UploadFile/Upload_Multiple.cshtml
@{
    ViewBag.Title = "Upload_Multiple";
}
@section scripts{
    <script>
        $(function () {
            function debug(msg) {
                var log = document.getElementById("debuglog");
                if (!log) {
                    log = document.createElement("div");
                    log.id = "debuglog";
                    log.innerHTML = "<hi>Debug Log</h1>";
                }
                var pre = document.createElement("pre");
                var text = document.createTextNode(msg);
                pre.appendChild(text);
                log.appendChild(pre);
            }
            debug("TEST JavaScript");
        })
        
        
    </script>
}
@*因為要上傳檔案enctype記得加上*@
@using (Html.BeginForm("Uploaded", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*因為要多個上傳 所以要用到multiple屬性*@
    <input type="file" name="files" multiple />
    <input type="submit" value="上傳" />
}

Mvc_Repository/Views/UploadFile/W3CScript.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>W3CScript</title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <style>
        *{
            padding:0;
            margin:0;
        }
        #ch12{
            width:500px;
        }
        .myClass{
            color:aqua;
            font-size:larger;
        }
        p {
            color: red;
        }
    </style>
</head>
<body>
    <form method="post" action="">
        <fieldset id="ch12">
            <div>
                <label for="two">2</label>
                <input type="checkbox" value="2" id="two" name="number">
            </div>
            <div>
                <label for="four">4</label>
                <input type="checkbox" value="4" id="four" name="number">
            </div>
            <div>
                <label for="six">6</label>
                <input type="checkbox" value="6" id="six" name="number">
            </div>
            <div>
                <label for="eight">8</label>
                <input type="checkbox" value="8" id="eight" name="number">
            </div>
        </fieldset>
        <button id="btn">觸發Change事件</button>
    </form>

    <p><b id="swich">Values: </b><span id="value"></span></p>
    <p>1</p>
    <p>23</p>
    <p>34</p>
    <p>4</p>
    <p>5</p>
    <p>6</p>
    <p>7</p>
    <p>8</p>
    <p>9</p>
    <p>0</p>
    <p>6</p>
    <p>5</p>
    <p>4</p>
    <p>5</p>
    <p>6</p>
    <p>3</p>
    <p>5</p>
    <p>6</p>
    <p>3</p>
    <p>5</p>
    <p id="position1">"0"</p>
    <p>76</p>
    <p>4</p>
    <p>3</p>
    <p>1</p>
    <p>2</p>
    <p>4</p>
    <p>4</p>
    <p>5</p>
    <p>7</p>
    <p>8</p>
    <p>9</p>
    <p>23</p>
    <p>45</p>
    <p>78</p>
    <p>90</p>
    
    <script>
        $(function () {
            $("#position1").text('"' + $(window).scrollTop() + '"');
            $("input[name=number]").change(function () {
                $("#swich").toggleClass("myClass");
                $("#value").empty();
                $("#value").append($("input[name=number]").map(function () {
                    if ($(this).is(":checked")) {
                        return this.id;
                    }
                }).get().join(','));
                var elt = $("#value");
                var win = $(document);
                $("#value").prepend("height :" + win.height() + "<br>");
                $("#value").prepend("innerHeight:" + win.innerHeight() + "<br>");
                $("#value").prepend("outerHeight :" + win.outerHeight() + "<br>");
                alert("!");
                
            })
            $("#btn").click(function (event) {
                $("input[name=number]").trigger("change");
                event.preventDefault();
            })
            $(window).scroll(function () {
                $("#position1").text('"' + ($(window).scrollTop() + $(window).innerHeight()) + '"');
            })
            
        })

    </script>
</body>
</html>